spring:
  application:
    name: user-service
  cloud:
    sentinel:
      transport:
        port: ${sentinel.transport.port.user-service}
        dashboard: ${sentinel.transport.dashboard}


server:
  port: ${user-service.port}


